### ISSUE TITLE
unable to download ryuk (fixed in #11)

### ISSUE THREAD

**Issue by cy4n** [sparsick/testcontainers-spring-boot#32]
hi Sandra 
the demo code won't work (found out in running the `HeroClassicJDBCRepositoryIT` tests, because the ryuk image can not be downloaded from quay.

fix comes with 1.14.3 (which should be available on merging #11 ), which adds a ryuk image from docker hub 

you can find the description and statement about the fix here:
https://github.com/testcontainers/testcontainers-java/issues/2763

**Comment by sparsick** [comment]
Hi Christian, 

thanks for your hint. I updated the dependencies, so code should work again.

Cheers,

Sandra
